### ISSUE TITLE
rsnapshot-scheduler dies silently

### ISSUE THREAD

**Issue by carlalexander** [debops/ansible-rsnapshot#20]
Running into this issue on a server.  Syslog says:

```
rsnapshot-scheduler[10278]: Scheduling daily backup of server.example.com using batch
```

Except nothing happens after, the script just dies. The lock file stays there too. So follow up executions don't work. 

But if I run `/usr/local/lib/rsnapshot-scheduler batchrun daily server.example.com` by hand, it works. So the `rsnapshot-scheduler` script should work too. Not sure why it dies there?

Any idea what might be causing that? Any log or trace that I can add?

**Comment by drybjed** [comment]
You can check the `at` queue under `root` account to see if there are any jobs scheduled - `atq`.

Apart from that, not sure... If you remove the lock file and let the `cron` schedule hourly backups, does that work?

**Comment by carlalexander** [comment]
It doesn't. It gets stuck again.

**Comment by carlalexander** [comment]
Here's what `atq` outputs:

```
322	Sun Dec 18 00:00:00 2016 b root
323	Sun Dec 25 00:00:00 2016 b root
324	Sun Jan  1 00:00:00 2017 b root
325	Sun Jan  8 00:00:00 2017 b root
326	Wed Jan 11 18:37:00 2017 R root
327	Wed Jan 11 20:34:00 2017 R root
328	Wed Jan 11 20:42:00 2017 R root
329	Thu Jan 12 06:25:00 2017 R root
331	Fri Jan 13 06:25:00 2017 R root
```

**Comment by drybjed** [comment]
Is the `rsnapshot` the only script that uses `batch` commands? Can you check if you can connect from the `rsnapshot` server to clients over SSH, via `root` account? Maybe the host fingerprint has changed? Does the host have correctly configured SMTP server so that mails from `cron` get to your mail account and have you got any messages from `cron` about this?

**Comment by carlalexander** [comment]
As far as, I know yes. `rsnapshot` connects fine since I'm running it by hand right now with this command under `root`:

```
$ /usr/local/lib/rsnapshot-scheduler batchrun daily server.example.com
```

I think cron is configured to send emails. I need to doublecheck.

**Comment by drybjed** [comment]
You could change the `cron` command to run the scheduler via `bash -x`, so that everything that the script does is output to stdout/stderr. Perhaps this will give some clues as to what might be wrong with the `cron` environment.

**Comment by carlalexander** [comment]
I managed to fix this by wiping the entire queue using:

```
$ for i in `atq | awk '{print $1}'`;do atrm $i;done
```
